// Glossary terms data - extracted from metallography.org/data/glossary.ts
const glossaryTerms = [
  // Microstructure Terms
  {
    term: 'Microstructure',
    definition: 'The internal structure of a material as observed under a microscope, including grains, phases, grain boundaries, and other features that determine material properties.',
    category: 'Microstructure',
    relatedTerms: ['Grain', 'Phase', 'Grain Boundary'],
    example: 'The microstructure of steel reveals ferrite and pearlite phases that determine its mechanical properties.',
  },
  {
    term: 'Grain',
    definition: 'An individual crystal within a polycrystalline material. Grains are separated by grain boundaries and their size significantly affects material properties such as strength and toughness.',
    category: 'Microstructure',
    relatedTerms: ['Grain Boundary', 'Grain Size', 'Polycrystalline'],
    example: 'Fine-grained materials typically exhibit higher strength than coarse-grained materials.',
  },
  {
    term: 'Grain Boundary',
    definition: 'The interface between adjacent grains where atoms are less regularly arranged. Grain boundaries can affect material properties and serve as sites for phase transformations.',
    category: 'Microstructure',
    relatedTerms: ['Grain', 'Grain Size'],
    example: 'Grain boundaries are often revealed by etching and appear as dark lines separating individual grains.',
  },
  {
    term: 'Grain Size',
    definition: 'A measure of the average size of grains in a material, typically expressed as ASTM grain size number or average grain diameter. Smaller grain sizes generally correlate with higher strength.',
    category: 'Microstructure',
    relatedTerms: ['Grain', 'ASTM Grain Size'],
    example: 'ASTM grain size number 8 indicates finer grains than grain size number 4.',
  },
  {
    term: 'Phase',
    definition: 'A distinct region in a material with uniform chemical composition and crystal structure. Materials can contain multiple phases (e.g., ferrite and cementite in steel).',
    category: 'Microstructure',
    relatedTerms: ['Microstructure', 'Ferrite', 'Cementite'],
    example: 'Steel contains multiple phases including ferrite (iron) and cementite (iron carbide).',
  },
  {
    term: 'Ferrite',
    definition: 'A body-centered cubic (BCC) phase of iron that contains little or no carbon. It is soft, ductile, and magnetic at room temperature.',
    category: 'Microstructure',
    relatedTerms: ['Phase', 'Cementite', 'Pearlite'],
    example: 'Low-carbon steels consist primarily of ferrite, giving them good ductility.',
  },
  {
    term: 'Cementite',
    definition: 'A hard, brittle phase of iron carbide (Fe3C) that forms in steel. Its appearance in etched microstructures depends on the etchant: with nital, ferrite and grain boundaries are attacked while cementite stands in relief and appears light/white; with picral, cementite is preferentially attacked and appears dark.',
    category: 'Microstructure',
    relatedTerms: ['Phase', 'Ferrite', 'Pearlite'],
    example: 'Cementite provides hardness to steel but reduces ductility.',
  },
  {
    term: 'Pearlite',
    definition: 'A lamellar microstructure consisting of alternating layers of ferrite and cementite. It forms during slow cooling of steel and provides a balance of strength and ductility.',
    category: 'Microstructure',
    relatedTerms: ['Ferrite', 'Cementite', 'Phase'],
    example: 'Eutectoid steel at room temperature consists entirely of pearlite.',
  },
  {
    term: 'Austenite',
    definition: 'A face-centered cubic (FCC) phase of iron that exists at high temperatures. On cooling it can transform to ferrite, pearlite, bainite, or martensite depending on the cooling rate and alloy composition.',
    category: 'Microstructure',
    relatedTerms: ['Phase', 'Martensite', 'Heat Treatment'],
    example: 'Steel is heated to the austenite region before quenching to form martensite.',
  },
  {
    term: 'Martensite',
    definition: 'A hard, supersaturated phase formed by diffusionless transformation of austenite during rapid cooling (quenching). In carbon steels it has a body-centered tetragonal (BCT) structure, with morphology that depends on carbon content: lath martensite forms in low-carbon steels (below about 0.6% C), while plate (often called needle-like in 2D section) martensite forms in higher-carbon steels. Provides high hardness but limited ductility until tempered.',
    category: 'Microstructure',
    relatedTerms: ['Austenite', 'Quenching', 'Heat Treatment'],
    example: 'Martensite formation requires rapid cooling to prevent transformation to softer phases.',
  },
  {
    term: 'Precipitate',
    definition: 'Small particles of a second phase that form within the primary phase, typically during aging or heat treatment. Precipitates can strengthen materials.',
    category: 'Microstructure',
    relatedTerms: ['Phase', 'Aging', 'Heat Treatment'],
    example: 'Aluminum alloys are strengthened by fine precipitates that form during aging.',
  },
  {
    term: 'Inclusion',
    definition: 'Non-metallic particles or compounds embedded in a metal matrix, typically oxides, sulfides, or silicates. Inclusions can affect material properties and machinability.',
    category: 'Microstructure',
    relatedTerms: ['Defect', 'Microstructure'],
    example: 'Manganese sulfide inclusions improve machinability in steel.',
  },
  {
    term: 'Defect',
    definition: 'Imperfections in material structure such as inclusions, voids, cracks, or dislocations that can affect material properties and performance.',
    category: 'Microstructure',
    relatedTerms: ['Inclusion', 'Void', 'Crack'],
  },
  {
    term: 'Bainite',
    definition: 'A microstructure formed by transformation of austenite at intermediate temperatures. Consists of ferrite and cementite with a characteristic acicular (needle-like) or feathery appearance.',
    category: 'Microstructure',
    relatedTerms: ['Ferrite', 'Cementite', 'Austenite'],
    example: 'Bainite forms at cooling rates between those that produce pearlite and martensite.',
  },
  {
    term: 'Widmanstätten Structure',
    definition: 'A microstructure characterized by needle-like or plate-like phases that form along specific crystallographic planes. Often seen in titanium alloys and some steels.',
    category: 'Microstructure',
    relatedTerms: ['Microstructure', 'Phase'],
  },
  {
    term: 'Dendrite',
    definition: 'A tree-like crystal structure that forms during solidification. Dendrites have a main trunk with branches extending outward.',
    category: 'Microstructure',
    relatedTerms: ['Microstructure', 'Solidification'],
  },
  {
    term: 'Eutectic',
    definition: 'A mixture of two or more phases that form simultaneously from a liquid at a specific composition and temperature. The lowest melting point composition for that system.',
    category: 'Microstructure',
    relatedTerms: ['Phase', 'Eutectoid'],
  },
  {
    term: 'Eutectoid',
    definition: 'A transformation where a single solid phase decomposes into two or more different solid phases at a specific temperature and composition.',
    category: 'Microstructure',
    relatedTerms: ['Phase', 'Eutectic', 'Pearlite'],
    example: 'Eutectoid steel (about 0.76 wt% C) transforms from austenite to pearlite at the eutectoid temperature, 727°C (1341°F).',
  },
  {
    term: 'Polycrystalline',
    definition: 'A material composed of many small crystals (grains) with different orientations. Most metals and alloys are polycrystalline.',
    category: 'Microstructure',
    relatedTerms: ['Grain', 'Crystal'],
  },
  {
    term: 'Recrystallization',
    definition: 'The nucleation and growth of new, strain-free grains that replace the deformed microstructure of a cold-worked material during heating. Driven by the stored energy of prior plastic deformation and typically observed at roughly 0.3 to 0.5 times the absolute melting temperature (in Kelvin). The exact onset temperature depends on alloy, prior strain, and time at temperature.',
    category: 'Microstructure',
    relatedTerms: ['Grain', 'Heat Treatment', 'Work Hardening'],
  },
  {
    term: 'Void',
    definition: 'An empty space or cavity within a material. Can be introduced during processing or form during service due to damage.',
    category: 'Microstructure',
    relatedTerms: ['Defect', 'Porosity'],
  },
  {
    term: 'Porosity',
    definition: 'The presence of voids or pores in a material, typically expressed as a percentage of void volume to total volume.',
    category: 'Microstructure',
    relatedTerms: ['Void', 'Defect'],
  },
  {
    term: 'Crack',
    definition: 'A fracture or separation in a material. Can be surface-breaking or internal. Critical defect that can lead to failure.',
    category: 'Microstructure',
    relatedTerms: ['Defect', 'Fracture'],
  },
  {
    term: 'Dislocation',
    definition: 'A line defect in the crystal structure of a material. Dislocations enable plastic deformation and affect material properties.',
    category: 'Microstructure',
    relatedTerms: ['Defect', 'Crystal'],
  },

  // Sample Preparation Terms
  {
    term: 'Sectioning',
    definition: 'The process of cutting a representative sample from a larger workpiece using abrasive or diamond cutting equipment. The first step in metallographic sample preparation.',
    category: 'Sample Preparation',
    relatedTerms: ['Mounting', 'Abrasive Cutting', 'Precision Wafering'],
    example: 'Sectioning should minimize damage and heat generation to preserve the true microstructure.',
  },
  {
    term: 'Abrasive Cutting',
    definition: 'A sectioning method using rotating abrasive wheels to cut through materials. Versatile and suitable for a wide range of materials and sizes.',
    category: 'Sample Preparation',
    relatedTerms: ['Sectioning', 'Precision Wafering'],
    example: 'Abrasive cutting is commonly used for standard metal samples and larger workpieces.',
  },
  {
    term: 'Precision Wafering',
    definition: 'A sectioning method using thin diamond or CBN blades to make precise, low-damage cuts. Ideal for delicate materials, thin sections, and applications requiring minimal damage.',
    category: 'Sample Preparation',
    relatedTerms: ['Sectioning', 'Abrasive Cutting'],
    example: 'Precision wafering is preferred for brittle materials like ceramics and semiconductors.',
  },
  {
    term: 'Mounting',
    definition: 'The process of embedding a sample in resin material to create a standardized, easy-to-handle mount. Makes samples easier to process through grinding, polishing, and analysis.',
    category: 'Sample Preparation',
    relatedTerms: ['Compression Mounting', 'Castable Mounting', 'Sectioning'],
    example: 'Mounting transforms irregularly shaped samples into uniform mounts suitable for automated processing.',
  },
  {
    term: 'Preparation',
    definition: 'The complete sequence of steps required to transform a raw material sample into a specimen suitable for microscopic examination. Includes sectioning, mounting, grinding, polishing, and etching.',
    category: 'Sample Preparation',
    relatedTerms: ['Sectioning', 'Mounting', 'Grinding', 'Polishing', 'Etching'],
    example: 'Proper preparation is essential for accurate microstructural analysis.',
  },
  {
    term: 'Compression Mounting',
    definition: 'A mounting method where resin pellets are heated and compressed under high pressure to form a solid mount. Fast (5-15 minutes) and produces hard, durable mounts.',
    category: 'Sample Preparation',
    relatedTerms: ['Mounting', 'Castable Mounting'],
    example: 'Compression mounting is ideal for high-throughput laboratories and standard metal samples.',
  },
  {
    term: 'Castable Mounting',
    definition: 'A mounting method where liquid resin is poured into a mold and allowed to cure at room temperature or with minimal heating. Ideal for delicate, heat-sensitive samples.',
    category: 'Sample Preparation',
    relatedTerms: ['Mounting', 'Compression Mounting'],
    example: 'Castable mounting is preferred for samples that cannot withstand high temperatures or pressure.',
  },
  {
    term: 'Grinding',
    definition: 'The process of removing sectioning damage and preparing the surface using progressively finer abrasives. Creates a uniform scratch pattern that can be removed during polishing.',
    category: 'Sample Preparation',
    relatedTerms: ['Polishing', 'Grit', 'Abrasive'],
    example: 'Grinding typically progresses from 120 grit to 600 or 1200 grit before polishing.',
  },
  {
    term: 'Grit',
    definition: 'A measure of abrasive particle size. Lower grit numbers indicate coarser abrasives, higher numbers indicate finer ones. Common standards (FEPA, ANSI/CAMI, JIS) are not directly interchangeable: the same grit number can correspond to very different particle sizes between systems. For example, FEPA P600 is roughly 25.8 µm, while ANSI/CAMI 600 is roughly 14.5 µm. When comparing papers or specifying a process, reference the actual µm size or the standard.',
    category: 'Sample Preparation',
    relatedTerms: ['Grinding', 'Abrasive', 'Grit Size'],
    example: 'Start grinding with 120 grit to remove sectioning damage, then progress to finer grits, checking the standard (FEPA "P" prefix vs ANSI) when matching consumables.',
  },
  {
    term: 'Polishing',
    definition: 'The stage of sample preparation that removes grinding damage and produces a flat, scratch-free surface suitable for etching and microscopy. Typically uses diamond abrasives for rough and intermediate polishing followed by an oxide suspension (commonly colloidal silica) for the final step. Best results combine complementary rotation of the platen and specimen holder to even out cutting action and minimize directional artifacts.',
    category: 'Sample Preparation',
    relatedTerms: ['Grinding', 'Diamond Polishing', 'Final Polishing'],
    example: 'A typical PACE ladder runs 6 μm diamond, then 3 μm and 1 μm diamond, finishing with a colloidal silica polish.',
  },
  {
    term: 'Diamond Polishing',
    definition: 'Polishing with diamond abrasives, applied as a paste, suspension, or aerosol spray onto an appropriate cloth. Common particle sizes are 9, 6, 3, 1, and 0.25 μm. Diamond is highly effective on both hard and soft phases because it cuts rather than rubs, producing low subsurface deformation when combined with adequate lubrication and complementary rotation.',
    category: 'Sample Preparation',
    relatedTerms: ['Polishing', 'Oxide Polishing'],
    example: 'A 6 μm diamond step quickly removes 600/1200-grit grinding scratches and is followed by 3 μm and 1 μm steps before final oxide polishing.',
  },
  {
    term: 'Oxide Polishing',
    definition: 'Final polishing using fine oxide suspensions (typically colloidal silica or alumina) to create a mirror-like, scratch-free surface. Removes any remaining fine scratches from diamond polishing.',
    category: 'Sample Preparation',
    relatedTerms: ['Polishing', 'Diamond Polishing', 'Final Polishing'],
    example: 'Oxide polishing with colloidal silica produces excellent results for most materials.',
  },
  {
    term: 'Etching',
    definition: 'The process of applying chemical reagents to reveal microstructural features. Etching attacks different phases and grain boundaries at different rates, creating contrast.',
    category: 'Sample Preparation',
    relatedTerms: ['Etchant', 'Microstructure'],
    example: 'Nital (nitric acid in alcohol) is commonly used to etch steel and reveal grain boundaries.',
  },
  {
    term: 'Etchant',
    definition: 'A chemical reagent used to etch (chemically attack) a polished sample surface to reveal microstructural features. Different etchants reveal different features.',
    category: 'Sample Preparation',
    relatedTerms: ['Etching', 'Reagent'],
    example: 'Kalling\'s No. 2 is used to reveal the microstructure of duplex, martensitic, and precipitation-hardening stainless steels; austenitic grades are more commonly etched with oxalic acid (electrolytic), aqua regia, or glyceregia.',
  },
  {
    term: 'Relief',
    definition: 'A polishing artifact where different phases or features stand above or below the polished surface due to different removal rates. Can be minimized with proper polishing technique.',
    category: 'Sample Preparation',
    relatedTerms: ['Polishing', 'Artifact'],
    example: 'Hard phases may stand in relief above softer phases if polishing pressure is too high.',
  },
  {
    term: 'Artifact',
    definition: 'A feature in a microstructure that is not part of the true material structure but is introduced during sample preparation. Examples include scratches, contamination, relief, and smearing.',
    category: 'Sample Preparation',
    relatedTerms: ['Relief', 'Scratch', 'Contamination'],
    example: 'Preparation artifacts must be distinguished from true microstructural features.',
  },
  {
    term: 'Smearing',
    definition: 'A polishing artifact where soft material is smeared across the surface, obscuring the true microstructure. Common in soft materials like aluminum and copper.',
    category: 'Sample Preparation',
    relatedTerms: ['Artifact', 'Polishing'],
    example: 'Smearing in aluminum can be prevented by using appropriate polishing cloths and techniques.',
  },
  {
    term: 'Abrasive',
    definition: 'Hard particles used for grinding and polishing. Common abrasives include silicon carbide, aluminum oxide, and diamond.',
    category: 'Sample Preparation',
    relatedTerms: ['Grinding', 'Polishing', 'Grit'],
  },
  {
    term: 'Coolant',
    definition: 'A fluid used during sectioning to reduce heat generation and prevent damage to the sample. Also helps remove cutting debris.',
    category: 'Sample Preparation',
    relatedTerms: ['Sectioning', 'Cutting'],
  },
  {
    term: 'Cutting Fluid',
    definition: 'A lubricant and coolant used during sectioning to reduce friction, heat, and tool wear. Helps produce cleaner cuts.',
    category: 'Sample Preparation',
    relatedTerms: ['Sectioning', 'Coolant'],
  },
  {
    term: 'Diamond Blade',
    definition: 'A thin cutting blade with diamond particles bonded to the edge. Used in precision wafering for low-damage sectioning.',
    category: 'Sample Preparation',
    relatedTerms: ['Precision Wafering', 'Sectioning'],
  },
  {
    term: 'CBN Blade',
    definition: 'Cubic Boron Nitride blade - a cutting blade with CBN particles bonded to the edge. Used for sectioning hard materials like tool steels.',
    category: 'Sample Preparation',
    relatedTerms: ['Precision Wafering', 'Diamond Blade'],
  },
  {
    term: 'Resin',
    definition: 'A synthetic polymer material used for mounting samples. Types include phenolic, epoxy, acrylic, and polyester resins.',
    category: 'Sample Preparation',
    relatedTerms: ['Mounting', 'Compression Mounting', 'Castable Mounting'],
  },
  {
    term: 'Mount',
    definition: 'A sample embedded in resin material, creating a standardized shape for easier handling during grinding, polishing, and analysis.',
    category: 'Sample Preparation',
    relatedTerms: ['Mounting', 'Resin'],
  },
  {
    term: 'Edge Retention',
    definition: 'The ability of a mount to maintain sharp edges and interfaces during grinding and polishing. Important for analyzing coatings, edges, or interfaces.',
    category: 'Sample Preparation',
    relatedTerms: ['Mounting', 'Compression Mounting'],
  },
  {
    term: 'Grit Progression',
    definition: 'The sequence of progressively finer grit sizes used during grinding. Typically progresses from coarse (120 grit) to fine (600-1200 grit).',
    category: 'Sample Preparation',
    relatedTerms: ['Grinding', 'Grit'],
  },
  {
    term: 'Scratch Pattern',
    definition: 'The pattern of scratches left on a sample surface after grinding. Should be uniform and oriented in one direction before moving to the next grit.',
    category: 'Sample Preparation',
    relatedTerms: ['Grinding', 'Grit'],
  },
  {
    term: 'Polishing Cloth',
    definition: 'A fabric pad used on polishing wheels to hold abrasives and provide appropriate surface texture. Different cloths have different nap levels and properties.',
    category: 'Sample Preparation',
    relatedTerms: ['Polishing', 'Diamond Polishing'],
  },
  {
    term: 'Polishing Pad',
    definition: 'A synthetic pad used for polishing, typically with a specific texture or nap designed for different polishing stages and materials.',
    category: 'Sample Preparation',
    relatedTerms: ['Polishing', 'Polishing Cloth'],
  },
  {
    term: 'Diamond Suspension',
    definition: 'Diamond particles suspended in a liquid carrier (water or oil-based) for polishing. Available in various particle sizes.',
    category: 'Sample Preparation',
    relatedTerms: ['Diamond Polishing', 'Polishing'],
  },
  {
    term: 'Colloidal Silica',
    definition: 'A fine oxide polishing suspension used for final polishing. Produces excellent surface finishes with minimal damage.',
    category: 'Sample Preparation',
    relatedTerms: ['Oxide Polishing', 'Final Polishing'],
  },
  {
    term: 'Immersion Etching',
    definition: 'An etching method where the sample is fully immersed in the etchant solution for a specified time.',
    category: 'Sample Preparation',
    relatedTerms: ['Etching', 'Etchant'],
  },
  {
    term: 'Swabbing',
    definition: 'An etching method where the etchant is applied to the sample surface using a cotton swab or similar applicator.',
    category: 'Sample Preparation',
    relatedTerms: ['Etching', 'Etchant'],
  },
  {
    term: 'Electrolytic Etching',
    definition: 'An etching method using electrical current to enhance the etching process. Used for some stainless steels and other materials.',
    category: 'Sample Preparation',
    relatedTerms: ['Etching', 'Etchant'],
  },
  {
    term: 'Contamination',
    definition: 'Foreign material introduced to the sample surface during preparation. Can include abrasive particles, polishing compounds, or other debris.',
    category: 'Sample Preparation',
    relatedTerms: ['Artifact', 'Polishing'],
  },
  {
    term: 'Scratch',
    definition: 'A linear mark or groove on the polished surface, typically from previous grinding steps that were not fully removed.',
    category: 'Sample Preparation',
    relatedTerms: ['Artifact', 'Grinding', 'Polishing'],
  },
  {
    term: 'Pitting',
    definition: 'Small holes or depressions in the polished surface, often caused by preferential etching or removal of inclusions.',
    category: 'Sample Preparation',
    relatedTerms: ['Artifact', 'Polishing'],
  },
  {
    term: 'Comet Tailing',
    definition: 'A polishing artifact in which hard, well-bonded particles (inclusions, carbides, intermetallics) shield a tail of softer matrix from abrasion, leaving comet-shaped streaks behind each particle. Typical root causes are excessive load, too-long step times, worn or contaminated cloths, and unidirectional motion. Reduced or eliminated by lowering load, refreshing abrasive, and using complementary rotation of the platen and specimen holder.',
    category: 'Sample Preparation',
    relatedTerms: ['Artifact', 'Polishing'],
  },

  // Equipment Terms
  {
    term: 'Abrasive Cutter',
    definition: 'Equipment used for sectioning samples using rotating abrasive wheels. Suitable for a wide range of materials and sample sizes.',
    category: 'Equipment',
    relatedTerms: ['Sectioning', 'Precision Wafering Saw'],
  },
  {
    term: 'Precision Wafering Saw',
    definition: 'Equipment used for precision sectioning with thin diamond or CBN blades. Produces low-damage cuts ideal for delicate materials.',
    category: 'Equipment',
    relatedTerms: ['Sectioning', 'Abrasive Cutter'],
  },
  {
    term: 'Mounting Press',
    definition: 'Equipment used for compression mounting. Applies heat and pressure to form solid mounts from resin pellets.',
    category: 'Equipment',
    relatedTerms: ['Compression Mounting', 'Mounting'],
  },
  {
    term: 'Grinding/Polishing Machine',
    definition: 'Equipment used for automated grinding and polishing of samples. Can be manual or fully automated with programmable parameters.',
    category: 'Equipment',
    relatedTerms: ['Grinding', 'Polishing'],
  },
  {
    term: 'Vibratory Polisher',
    definition: 'Equipment that uses vibration to polish samples. Eliminates subsurface damage and produces superior surface finishes, ideal for EBSD preparation.',
    category: 'Equipment',
    relatedTerms: ['Polishing', 'Vibratory Polishing'],
  },
  {
    term: 'Metallographic Microscope',
    definition: 'A microscope designed for observing polished and etched metallographic samples. Typically includes reflected light illumination and various magnification options.',
    category: 'Equipment',
    relatedTerms: ['Microstructure', 'Analysis'],
  },
  {
    term: 'Cut-Off Wheel',
    definition: 'An abrasive wheel used for sectioning samples. Available in various diameters and abrasive types.',
    category: 'Equipment',
    relatedTerms: ['Abrasive Cutter', 'Sectioning'],
  },
  {
    term: 'Wafering Blade',
    definition: 'A thin blade with diamond or CBN particles used in precision wafering. Much thinner than abrasive wheels.',
    category: 'Equipment',
    relatedTerms: ['Precision Wafering Saw', 'Diamond Blade'],
  },
  {
    term: 'Mounting Mold',
    definition: 'A container or form used to hold the sample and resin during mounting. Can be reusable or disposable.',
    category: 'Equipment',
    relatedTerms: ['Mounting', 'Compression Mounting', 'Castable Mounting'],
  },
  {
    term: 'Vacuum Chamber',
    definition: 'Equipment used in castable mounting to remove air bubbles from liquid resin before curing. Ensures porosity-free mounts.',
    category: 'Equipment',
    relatedTerms: ['Castable Mounting', 'Mounting'],
  },
  {
    term: 'Polishing Wheel',
    definition: 'A rotating disc used for polishing samples. Holds polishing cloths or pads and rotates at controlled speeds.',
    category: 'Equipment',
    relatedTerms: ['Polishing', 'Polishing Cloth'],
  },
  {
    term: 'Optical Microscope',
    definition: 'A microscope that uses visible light to observe samples. Standard tool for metallographic analysis at magnifications up to 1000x.',
    category: 'Equipment',
    relatedTerms: ['Metallographic Microscope', 'Microstructure'],
  },
  {
    term: 'Hardness Tester',
    definition: 'Equipment used to measure material hardness by indentation. Types include Rockwell, Brinell, Vickers, and Knoop testers.',
    category: 'Equipment',
    relatedTerms: ['Hardness', 'Hardness Testing'],
  },

  // Material Science Terms
  {
    term: 'Alloy',
    definition: 'A metallic material composed of two or more elements, at least one of which is a metal. Alloys typically have improved properties compared to pure metals.',
    category: 'Material Science',
    relatedTerms: ['Metal', 'Composition'],
    example: 'Steel is an alloy of iron and carbon, often with additional alloying elements.',
  },
  {
    term: 'Heat Treatment',
    definition: 'Controlled heating and cooling processes used to alter material properties. Common treatments include annealing, quenching, tempering, and aging.',
    category: 'Material Science',
    relatedTerms: ['Annealing', 'Quenching', 'Tempering'],
    example: 'Heat treatment can increase hardness, strength, or improve machinability.',
  },
  {
    term: 'Annealing',
    definition: 'A heat treatment process that involves heating a material to a specific temperature and slowly cooling it to soften the material, relieve stresses, or alter microstructure.',
    category: 'Material Science',
    relatedTerms: ['Heat Treatment', 'Quenching'],
    example: 'Annealing is used to soften cold-worked materials and improve ductility.',
  },
  {
    term: 'Quenching',
    definition: 'Rapid cooling of a material from high temperature, typically in water, oil, or air. Used to form hard phases like martensite in steel.',
    category: 'Material Science',
    relatedTerms: ['Heat Treatment', 'Martensite', 'Tempering'],
    example: 'Rapid quenching of steel from the austenite region forms hard martensite.',
  },
  {
    term: 'Tempering',
    definition: 'A heat treatment process where quenched steel is reheated to a temperature below the transformation range to reduce brittleness and adjust hardness.',
    category: 'Material Science',
    relatedTerms: ['Heat Treatment', 'Quenching', 'Martensite'],
    example: 'Tempering reduces the brittleness of martensite while maintaining high strength.',
  },
  {
    term: 'Hardness',
    definition: 'A measure of a material\'s resistance to deformation, typically measured by indentation. Common scales include Rockwell (HRC, HRB), Brinell (HB), and Vickers (HV).',
    category: 'Material Science',
    relatedTerms: ['Hardness Testing', 'Rockwell', 'Brinell', 'Vickers'],
    example: 'Hardness testing is a quick way to assess material properties without destructive testing.',
  },
  {
    term: 'Work Hardening',
    definition: 'The increase in hardness and strength of a material due to plastic deformation. Also called strain hardening or cold working.',
    category: 'Material Science',
    relatedTerms: ['Hardness', 'Deformation'],
    example: 'Work hardening occurs when metals are deformed at temperatures below the recrystallization temperature.',
  },
  {
    term: 'Metal',
    definition: 'A class of materials characterized by metallic bonding, high electrical and thermal conductivity, and typically good ductility and strength.',
    category: 'Material Science',
    relatedTerms: ['Alloy'],
  },
  {
    term: 'Steel',
    definition: 'An alloy of iron and carbon, typically containing less than 2% carbon. May also contain other alloying elements.',
    category: 'Material Science',
    relatedTerms: ['Alloy', 'Iron', 'Carbon'],
  },
  {
    term: 'Stainless Steel',
    definition: 'A steel alloy containing at least 10.5% chromium. Corrosion resistance comes from a thin, self-healing passive film of chromium oxide (Cr2O3) that forms on the surface. May also contain nickel, molybdenum, manganese, nitrogen, and other elements, with major families including austenitic, ferritic, martensitic, duplex, and precipitation-hardening (PH) grades.',
    category: 'Material Science',
    relatedTerms: ['Steel', 'Alloy'],
  },
  {
    term: 'Aging',
    definition: 'A heat treatment process where a material is held at an elevated temperature to allow precipitates to form, strengthening the material.',
    category: 'Material Science',
    relatedTerms: ['Heat Treatment', 'Precipitate'],
    example: 'Aluminum alloys are aged to form strengthening precipitates.',
  },
  {
    term: 'Solution Treatment',
    definition: 'A heat treatment where alloying elements are dissolved into solid solution by heating, followed by rapid cooling to retain the solution.',
    category: 'Material Science',
    relatedTerms: ['Heat Treatment', 'Aging'],
  },
  {
    term: 'Normalizing',
    definition: 'A heat treatment process where steel is heated above the transformation temperature and air-cooled to refine grain structure.',
    category: 'Material Science',
    relatedTerms: ['Heat Treatment', 'Annealing'],
  },
  {
    term: 'Rockwell Hardness',
    definition: 'A hardness testing method using different scales (HRC, HRB, etc.) based on indenter type and load. Quick and widely used.',
    category: 'Material Science',
    relatedTerms: ['Hardness', 'Hardness Testing'],
  },
  {
    term: 'Brinell Hardness',
    definition: 'A hardness testing method using a spherical indenter. Expressed as HB. Good for softer materials and rough surfaces.',
    category: 'Material Science',
    relatedTerms: ['Hardness', 'Hardness Testing'],
  },
  {
    term: 'Vickers Hardness',
    definition: 'A hardness testing method using a square-based diamond pyramid indenter with a 136° included angle between opposite faces (ASTM E92, E384 for microindentation). HV is calculated from the applied load and the mean diagonal of the indentation. A single continuous scale spans soft metals to hardened steels and ceramics, making it well suited to comparative work across material classes.',
    category: 'Material Science',
    relatedTerms: ['Hardness', 'Hardness Testing'],
  },
  {
    term: 'Knoop Hardness',
    definition: 'A microindentation hardness method (ASTM E384) using a rhombic-based diamond pyramid with included angles of 172.5° and 130°, producing a long, shallow indentation with a long-to-short diagonal ratio of about 7:1. The shallow indent makes Knoop preferable to Vickers for thin coatings, case-hardened layers, brittle materials, and measurements near edges, and the elongated shape allows detection of mechanical anisotropy.',
    category: 'Material Science',
    relatedTerms: ['Hardness', 'Hardness Testing'],
  },
  {
    term: 'Tensile Strength',
    definition: 'The maximum stress a material can withstand while being stretched before failure. Also called ultimate tensile strength (UTS).',
    category: 'Material Science',
    relatedTerms: ['Strength', 'Mechanical Properties'],
  },
  {
    term: 'Yield Strength',
    definition: 'The stress at which a material begins to deform plastically. The point where permanent deformation occurs.',
    category: 'Material Science',
    relatedTerms: ['Strength', 'Tensile Strength'],
  },
  {
    term: 'Ductility',
    definition: 'The ability of a material to deform plastically before fracture. Measured as percent elongation or percent reduction in area.',
    category: 'Material Science',
    relatedTerms: ['Mechanical Properties'],
  },
  {
    term: 'Toughness',
    definition: 'The ability of a material to absorb energy and deform plastically before fracture. Combines strength and ductility.',
    category: 'Material Science',
    relatedTerms: ['Strength', 'Ductility'],
  },
  {
    term: 'Brittleness',
    definition: 'The tendency of a material to fracture without significant plastic deformation. Opposite of ductility.',
    category: 'Material Science',
    relatedTerms: ['Ductility', 'Fracture'],
  },

  // Analysis Terms
  {
    term: 'ASTM Grain Size',
    definition: 'A standardized system (ASTM E112) for describing grain size, with grain size number G ranging from 00 (very coarse) through about 14 (very fine). G is defined by N = 2^(G-1), where N is the number of grains per square inch observed at 100x magnification. Higher G numbers indicate finer grains. Comparable to ISO 643.',
    category: 'Analysis',
    relatedTerms: ['Grain Size', 'Grain', 'Intercept Method', 'Planimetric Method'],
    example: 'ASTM grain size number 8 indicates finer grains than grain size number 4 (each unit increase in G roughly doubles the grains-per-area at 100x).',
  },
  {
    term: 'Magnification',
    definition: 'The degree to which an image is enlarged when viewed through a microscope. Expressed as a ratio (e.g., 100x means 100 times larger than actual size).',
    category: 'Analysis',
    relatedTerms: ['Microscope', 'Microstructure'],
    example: 'Grain boundaries are typically visible at magnifications of 100x to 500x.',
  },
  {
    term: 'EBSD',
    definition: 'Electron Backscatter Diffraction, a technique used in the SEM to map crystal orientation, grain boundaries, phase distribution, and local strain. The sample is tilted to about 70° and Kikuchi patterns from the surface are indexed pixel by pixel. EBSD is extremely sensitive to residual deformation, so it requires a strain-free surface, typically achieved through long-duration vibratory polishing or extended colloidal silica polishing after the standard diamond ladder.',
    category: 'Analysis',
    relatedTerms: ['SEM', 'Microstructure', 'Vibratory Polisher', 'Colloidal Silica'],
    example: 'A 4-12 hour vibratory polish with colloidal silica is commonly used as the final step before EBSD mapping.',
  },
  {
    term: 'SEM',
    definition: 'Scanning Electron Microscope - a type of electron microscope that produces high-resolution images of sample surfaces. Provides higher magnification than optical microscopes.',
    category: 'Analysis',
    relatedTerms: ['Microscope', 'EBSD'],
    example: 'SEM analysis reveals surface features at much higher magnifications than optical microscopy.',
  },
  {
    term: 'TEM',
    definition: 'Transmission Electron Microscope - an electron microscope that transmits electrons through thin samples. Provides very high resolution and magnification.',
    category: 'Analysis',
    relatedTerms: ['SEM', 'Microscope'],
  },
  {
    term: 'EDS',
    definition: 'Energy-Dispersive X-ray Spectroscopy - a technique used in SEM to identify and quantify chemical elements in a sample.',
    category: 'Analysis',
    relatedTerms: ['SEM', 'Analysis'],
  },
  {
    term: 'WDS',
    definition: 'Wavelength-Dispersive X-ray Spectroscopy, an elemental analysis technique used in the SEM or electron microprobe. A diffracting crystal selects a single X-ray wavelength at a time, giving much higher spectral resolution than EDS (about 5-20 eV vs 130-150 eV) and significantly better sensitivity for light elements and trace constituents. Acquisition is serial rather than parallel, so analyses are slower and the instrument is more complex than an EDS detector.',
    category: 'Analysis',
    relatedTerms: ['SEM', 'EDS'],
  },
  {
    term: 'Image Analysis',
    definition: 'The use of software to automatically measure and analyze microstructural features from digital images. Can quantify grain size, phase fractions, etc.',
    category: 'Analysis',
    relatedTerms: ['Microstructure', 'Grain Size'],
  },
  {
    term: 'Phase Fraction',
    definition: 'The percentage or fraction of each phase present in a material. Measured using image analysis or point counting methods.',
    category: 'Analysis',
    relatedTerms: ['Phase', 'Image Analysis'],
  },
  {
    term: 'Point Counting',
    definition: 'A manual method for determining phase fractions by counting points that fall on each phase in a grid overlay.',
    category: 'Analysis',
    relatedTerms: ['Phase Fraction', 'Microstructure'],
  },
  {
    term: 'Intercept Method',
    definition: 'A method for measuring grain size by counting the number of grain boundaries intersected by test lines.',
    category: 'Analysis',
    relatedTerms: ['Grain Size', 'ASTM Grain Size'],
  },
  {
    term: 'Planimetric Method',
    definition: 'A method for measuring grain size by counting the number of grains within a known area.',
    category: 'Analysis',
    relatedTerms: ['Grain Size', 'ASTM Grain Size'],
  },

  // General Terms
  {
    term: 'Metallography',
    definition: 'The study of the microstructure of metals and alloys using microscopy. Involves sample preparation (sectioning, mounting, grinding, polishing, etching) and microscopic examination.',
    category: 'General',
    relatedTerms: ['Microstructure', 'Sample Preparation'],
    example: 'Metallography is essential for understanding material properties and quality control.',
  },
  {
    term: 'Metallurgist',
    definition: 'A scientist or engineer who studies the physical and chemical behavior of metals and alloys, including their structure, properties, and processing.',
    category: 'General',
    relatedTerms: ['Metallography'],
  },
  {
    term: 'Metallographer',
    definition: 'A specialist who prepares and examines metallographic samples. Skilled in sample preparation techniques and microstructural analysis.',
    category: 'General',
    relatedTerms: ['Metallography', 'Metallurgist'],
  },
];

